### ISSUE TITLE
Post API to send confession

### ISSUE THREAD

**Issue by iharshit009** [iharshit009/SecretPeek#1]
We need to create a POST API for submitting the two fields:
1. name
2. message. 

If you are new to Flask, do check out this tutorial: https://blog.miguelgrinberg.com/post/designing-a-restful-api-with-python-and-flask

**Comment by iharshit009** [comment]
@pratyaa Any updates?

**Comment by Rits1272** [comment]
@iharshit009 can I work on this issue? I have good hands in developing REST APIs using flask

**Comment by iharshit009** [comment]
Okay, @Rits1272 go ahead with it, ping me on slack for your doubts, if any.
