### ISSUE TITLE
Mention Read Count

### ISSUE THREAD

**Issue by iharshit009** [iharshit009/SecretPeek#10]
Develop a read count on the bottom right of each confession, indicating the no of reads of each confession
![Read Count](https://user-images.githubusercontent.com/44135316/101309682-f1daaf00-3872-11eb-9250-1090cb31fd8c.jpeg)

**Comment by iharshit009** [comment]
@mastershailesh1234 Hey would you like to take this frontend issue?
If you want to work on any other one, do let me know.

**Comment by mastershailesh1234** [comment]
@iharshit009  thanks for letting me work. i would like to work on this issue.

**Comment by iharshit009** [comment]
@mastershailesh1234  great, Please go ahead working on this. For any doubts ping me anytime.
