### ISSUE TITLE
Convert Webapp to PWA

### ISSUE THREAD

**Issue by iharshit009** [iharshit009/SecretPeek#11]
Currently, our app is a usual webpage. We need to convert it a PWA(Progressive Web App).
For this we need to make some changes in our html file and add some additional details as well.

If you are new or don't know about PWA, go and read this out: https://wiredelta.com/how-to-turn-a-website-into-a-pwa/
This article contains all the question and that may occur in your mind. You could follow up the steps mentioned to work on this issue.

**Comment by chinmaym07** [comment]
Hey @iharshit009  Can I try this .?

**Comment by iharshit009** [comment]
Yes, go ahead with it.
If you have any questions please let me know(ping me on slack)

Harshit Jain

**Comment by iharshit009** [comment]
@chinmaym07 any updates?

**Comment by chinmaym07** [comment]
Hey @iharshit009  I am working on it ..will try to complete asap .👍🏻

**Comment by chinmaym07** [comment]
![Peek 2020-12-11 03-41](https://user-images.githubusercontent.com/44670961/101836346-3d3ad900-3b63-11eb-96fb-98c0f4cb068d.gif)

Shall I open a pr ?..I have not hosted it (production) .

**Comment by iharshit009** [comment]
@chinmaym07 Yaa sure
