### ISSUE TITLE
GET API to receive all confessions

### ISSUE THREAD

**Issue by iharshit009** [iharshit009/SecretPeek#2]
Currently, the API used to receive data is from a dummy API developed in Django. Here we need to create a GET API for two fields:
1. name
2. message. 
Dummy API(Django): https://gsconfessions.herokuapp.com/

If you are new to Flask, do check out this tutorial: https://blog.miguelgrinberg.com/post/designing-a-restful-api-with-python-and-flask

**Comment by paramsiddharth** [comment]
Do we need to create the API in Flask? If yes, should we create a new directory and make it therein?

**Comment by iharshit009** [comment]
Yes @paramsiddharth  we need to create an API in flask. Create a dir and go ahead with it.
For any query, ping me on Slack(link in Readme)

**Comment by iharshit009** [comment]
@paramsiddharth  Any updates? Are you stuck at some point and need help?

**Comment by Rits1272** [comment]
Can I work on this issue @iharshit009?

**Comment by paramsiddharth** [comment]
> @paramsiddharth Any updates? Are you stuck at some point and need help?

No no, I'm not stuck at all. I have worked with Flask before, and I'm working on the API too.

**Comment by iharshit009** [comment]
Okay, till when can I expect a PR?

Harshit Jain

**Comment by paramsiddharth** [comment]
You can expect a PR within 2 working days.
