### ISSUE TITLE
Create a Text Input to write

### ISSUE THREAD

**Issue by iharshit009** [iharshit009/SecretPeek#3]
Develop an Input Text(not more than 200 char) at the bottom of the Page, where the user can write a message to post and a name(for the person the confession is posted)

**Comment by mastershailesh1234** [comment]
Can i work on this issue?

**Comment by iharshit009** [comment]
Yes @mastershailesh1234, you can work, Go ahead.
For any query, ping me on Slack(link in Readme)

**Comment by iharshit009** [comment]
@mastershailesh1234  Any updates? Are you stuck at some point and need help?

**Comment by mastershailesh1234** [comment]
@iharshit009 i learnt flask basics with in this 2 days and now i am learning some stuffs related to API and socket io. 1-2 days then i would work on my issue. i got confused seeing the codes😅 thats why i thought it would be good to work on issue after learning.

**Comment by iharshit009** [comment]
Don't worry, you will get it with time.
It's great that you are learning.

But this issue don't have any relation with flask or sockets..

It's a completely frontend related issue, with could be completed with
basic knowledge of HTML, CSS and JS.

Kindly read the issue again'.

Harshit Jain
