### ISSUE TITLE
[Optional] Dockerize The Project

### ISSUE THREAD

**Issue by iharshit009** [iharshit009/SecretPeek#4]
This is totally a learning opportunity for the students to learn Docker.

We can dockerize the entire project using [Docker](https://www.docker.com/) and make it available on[ Docker Hub](https://hub.docker.com/).

We can also expose accepting three arguments from the user to the Docker container and then pass it on to the script.

Resources:

https://runnable.com/docker/python/dockerize-your-flask-application
https://stackoverflow.com/questions/34254200/how-to-pass-arguments-to-a-dockerfile

**Comment by paramsiddharth** [comment]
I would like to work on this.

**Comment by iharshit009** [comment]
Please work first on developing the core functionality of the app, and than later on you could do this

**Comment by ineffable23** [comment]
I'm highly interested to work on this issue

**Comment by iharshit009** [comment]
@paramsiddharth would you like to take this issue or not?

**Comment by paramsiddharth** [comment]
> @paramsiddharth would you like to take this issue or not?

Yes! I would like to take it.

**Comment by iharshit009** [comment]
@paramsiddharth assigned this issue, please continue your work

**Comment by paramsiddharth** [comment]
@iharshit009 #19 needs to be completed before I can create the `Dockerfile`. Will you be doing it?

**Comment by iharshit009** [comment]
https://github.com/iharshit009/SecretPeek/blob/main/requirements.txt

Is this not the one you are referring to?

Harshit Jain

**Comment by paramsiddharth** [comment]
> @iharshit009 #19 needs to be completed before I can create the `Dockerfile`. Will you be doing it?

Pardon! I must've missed it. I will go ahead with the `Dockerfile`.
