### ISSUE TITLE
Like Icon for Confessions

### ISSUE THREAD

**Issue by iharshit009** [iharshit009/SecretPeek#7]
Just as you like a message on Instagram, we need to build it for each and every confession.

![like](https://user-images.githubusercontent.com/44135316/101287702-e60dcf00-3817-11eb-8855-98a56c09866b.jpg)

Double-tap a Confession will like it
Again giving a double tap on the same confession would remove the like from that particular confession

As our project takes Anonymity very seriously, so as Instagram we will not be having a feature to show who liked, we would be showing the count of likes for each confession
If no like then nothing would be shown
If one, then just a heart as shown in the above image
If two or more, than just add up a number beside the heart

**Comment by ineffable23** [comment]
I'd love to work on this issue

**Comment by iharshit009** [comment]
Go ahead with it. All the best

Harshit Jain

**Comment by iharshit009** [comment]
@ineffable23  Any Updates on this?

**Comment by ineffable23** [comment]
Yup, I'm working on it.

**Comment by chinmaym07** [comment]
Hey @iharshit009  can I give this a try.
if this issue is not completed .?

**Comment by iharshit009** [comment]
@chinmaym07 I am sorry for replying late. Yes, you could work on this issue.
I suppose @ineffable23 would not work on this issue

**Comment by chinmaym07** [comment]
Hey @iharshit009,Currently, the response that we are getting from the api does not have an attribute for likes count.
But it is required then only if(like == 0) then will only show heart icon as above & if it is greater than 0 then we will show the count beside heart.

**Comment by iharshit009** [comment]
Just work for one(when there is one like) and later on when the API is available, we could start working on indicating the count too

**Comment by chinmaym07** [comment]
Hey @iharshit009  I have Implemented above task as below 
Added a double click event on the card and a single click event on the Heart icon same as in instagram . 

![Peek 2020-12-25 20-01](https://user-images.githubusercontent.com/44670961/103137128-404dd180-46ec-11eb-9ab5-c1f559ccf563.gif)


If it worked for you. Can I open a pr for the same. ?

**Comment by iharshit009** [comment]
Yeah sure, you can create a PR

Harshit Jain
