### ISSUE TITLE
Removing Stopwords from Confessions

### ISSUE THREAD

**Issue by iharshit009** [iharshit009/SecretPeek#8]
Anonymity may give rise to Profanity, therefore we may need to either remove/replace them or don't allow them to post.
A list of Stopwords could be discussed. Suggestions in this regard are welcomed.

**Comment by Rits1272** [comment]
Should we use a Machine Learning Classifier to remove stopwords? @iharshit009

**Comment by iharshit009** [comment]
Please elaborate.

Harshit Jain
