### ISSUE TITLE
Mention timestamp in Confession

### ISSUE THREAD

**Issue by iharshit009** [iharshit009/SecretPeek#9]
Develop a timestamp on the bottom right of each confession, indicating the day and time of the confession posted.
For eg:
![timestamp](https://user-images.githubusercontent.com/44135316/101309415-606b3d00-3872-11eb-9520-d0194ab6275f.jpeg)

**Comment by verma-shivani** [comment]
I would like to work on this issue.Please,assign this to me.

**Comment by iharshit009** [comment]
Please go ahead working on this, ping me on slack with your doubts, if any.

Harshit Jain
